### ISSUE TITLE
New Update is crashing for me at start of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [Theoness1/PelmenMod#2]
.

**Comment by Theoness1** [comment]
Sorry. I don't like links. There is no crash on 1.19, is it on 1.18.2?

**Comment by TheButterbrotMan** [comment]
Yes, only 1.18.2. The link was just the log. lol.

**Comment by PinkGoosik** [comment]
oh no scary link

**Comment by Theoness1** [comment]
fixed

**Comment by TheButterbrotMan** [comment]
Thank you! :)

**Comment by TheButterbrotMan** [comment]
@Theoness1 Still crashing. 2.2 does not work.

**Comment by Theoness1** [comment]
> @Theoness1 Still crashing. 2.2 does not work.

WHATY

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/Z3589n1Dip (Sorry for Link. Lol.)

**Comment by PinkGoosik** [comment]
redownload 2.1 please

**Comment by TheButterbrotMan** [comment]
This bug is still present, any progress on fixing this? @Theoness1

**Comment by Theoness1** [comment]
> This bug is still present, any progress on fixing this? @Theoness1

???

**Comment by TheButterbrotMan** [comment]
> > This bug is still present, any progress on fixing this? @Theoness1
> 
> ???

What?
